### PR TITLE
Added a fix to Capistrano::Configuration.instance sometimes not being available

### PR DESCRIPTION
**Pull request by cbetta**
This is a fix to the problem described in issue #1

### CODE REVIEW

**Comment by cbetta** [comment]
The diff is slightly unreadable because I had to change the indentation, but it pretty much is just a 2-line change. I wrapped the loading block in an if statement to check if `Capistrano::Configuration.instance` is nil

**Comment by cbetta** [comment]
Mind shipping this as a new version of the gem?

**Comment by teohm** [comment]
@cbetta Sorry for the long delay! Your patch is now available in the latest version, thanks for your PR:

http://rubygems.org/gems/capistrano-shared_file

I'm not actively working on this project now. If you are interested, this project needs a new owner :)

**Comment by cbetta** [comment]
:+1: Not sure I will have the time for any development, but happy to vet/merge any PRs as they come in. Easiest probably to just add me as a collab here and on rubygems

**Comment by teohm** [comment]
@cbetta Added you as a GH collab, which email should i add you as rubygems owner?

**Comment by cbetta** [comment]
Tnx @teohm, that would be cbetta@gmail.com

**Comment by teohm** [comment]
@cbetta added you as capistrano-shared_file gem owner on Rubygems

https://rubygems.org/gems/capistrano-shared_file

**Comment by cbetta** [comment]
Cheers, thank you.

**Pull request merged**
